### ISSUE TITLE
Understanding Avocado

### ISSUE THREAD

**Issue by ssbanerje** [bigdatagenomics/avocado#108]
I am trying to understand how Avocado works. Is there a documentation page for how the code (the master branch) is laid out?

I am looking at a report available online (http://www.cs.berkeley.edu/~kubitron/courses/cs262a-F13/projects/reports/project8_report.pdf), and trying to map what I read there to the code in the repository. But it seems that things have somewhat diverged from the report.

For example, where do the assembly based calls happen? There seems to be something in the `algorithms/` folder, but nothing seems to call it. Does the `master` branch do the read based calls?

Maybe I am missing something here, could you guys point me to any resources that clears this up?

**Comment by fnothaft** [comment]
Sorry, took a while to get to this! I'll have a PR that adds a good amount of documentation to avocado coming along sometime this week.
