### ISSUE TITLE
The build should use the version 0.1.3-SNAPSHOT of bdg-utils-metrics:jar

### ISSUE THREAD

**Issue by davidonlaptop** [bigdatagenomics/avocado#144]
## Issue
Currently maven looks for version 0.1.2-SNAPSHOT, but apparently this artefact cannot be found.

## Steps to reproduce:
1. Fetch master branch
2. mvn package

## Error Output
[ERROR] Failed to execute goal on project avocado-core: Could not resolve dependencies for project org.bdgenomics.avocado:avocado-core:jar:0.0.3-SNAPSHOT: The following artifacts could not be resolved: org.bdgenomics.bdg-utils:bdg-utils-metrics:jar:0.1.2-SNAPSHOT, org.bdgenomics.bdg-utils:bdg-utils-misc:jar:tests:0.1.2-SNAPSHOT: Could not find artifact org.bdgenomics.bdg-utils:bdg-utils-metrics:jar:0.1.2-SNAPSHOT in Sonatype (http://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]

## Potential resolution
Use the new version that is available: https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/bdg-utils/bdg-utils-metrics/

Change line 26 of pom.xml as follows:
 `<utils.version>0.1.3-SNAPSHOT</utils.version>`

**Comment by fnothaft** [comment]
Ah, yes! Thanks for catching this; we made a new release of bdg-utils two days ago, so the 0.1.2-SNAPSHOT is not still available.

**Comment by fnothaft** [comment]
Closed by #145.
