### ISSUE TITLE
Add unsupervised variant filtration method.

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/avocado#161]
Since #153 was added, we can now make use of an unsupervised method for filtering out variants. This would probably be done via a VQSR-like method. @andrewmchen is working on this, IIRC.

**Comment by dmyersturnbull** [comment]
@andrewmchen I'm only just learning about Adam and Avocado, but I'm happy to lend a hand. Is there anything specific that needs to be written? I've been looking over the relevant commits.
