### ISSUE TITLE
Cannot load properties file on YARN

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/avocado#175]
Right now, we rely on the property config file to be local to the driver. This doesn't work in YARN, since the driver may not be the machine that the job is launched from.

**Comment by heuermh** [comment]
Was this fixed by #177 or did you want to leave it open until you find a "better" way to solve the problem?  :)

**Comment by fnothaft** [comment]
Yes, it was. I thought it'd get closed when #177 merged. Alas!
