### ISSUE TITLE
Cross compile scala 2.10/2.11 and provide separate artifacts

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/avocado#176]
Similar to
https://github.com/bigdatagenomics/adam/blob/master/scripts/move_to_scala_2.10.sh
https://github.com/bigdatagenomics/adam/blob/master/scripts/move_to_scala_2.11.sh
https://github.com/bigdatagenomics/adam/blob/master/scripts/release/release.sh

**Comment by fnothaft** [comment]
@heuermh If you want to tackle this, that'd be great! However, I would urge you to wait until Monday ;) as I am hoping to have two fixes for #174 and #175 pushed today, and I think there might be conflicts between the two.

**Comment by heuermh** [comment]
Just wanted to note this as something that needed to be done, after #174 certainly.

**Comment by fnothaft** [comment]
Resolved by https://github.com/bigdatagenomics/avocado/commit/35c17805518bd6a80327ff8e93f8447be1acf3ff.
