### ISSUE TITLE
GenotypeLikelihoods should be log10 Scaled Probabilities 

### ISSUE THREAD

**Issue by andrewmchen** [bigdatagenomics/avocado#178]
In our genotyper [BiallelicGenotyper.scala](https://github.com/bigdatagenomics/avocado/blob/master/avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala#L258) we are phred scaling likelihoods. However from the VCF specification it says that the GL fields should be log-10 scaled likelihoods.

> GL : genotype likelihoods comprised of comma separated floating point log10-scaled likelihoods for all possible genotypes given the set of alleles defined in the REF and ALT fields. In presence of the GT field the same ploidy is expected and the canonical order is used; without GT field, diploidy is assumed. If A is the allele in REF and B,C,... are the alleles as ordered in ALT, the ordering of genotypes for the likelihoods is given by:
> F(j/k) = (k*(k+1)/2)+j. In other words, for biallelic sites the ordering is: AA,AB,BB; for triallelic sites the ordering is: AA,AB,BB,AC,BC,CC, etc. For example: GT:GL 0/1:-323.03,-99.29,-802.53 (Floats)

http://samtools.github.io/hts-specs/VCFv4.1.pdf

**Comment by fnothaft** [comment]
In bdg-formats:0.4.0, which is what we are on, the `Genotype.genotypeLikelihood` field maps to `PL`, which is the Phred scaled genotype likelihood, not `GL` (see https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala#L347). In bdg-formats:0.6.0 (which will be in adam:0.18.0), `Genotype.genotypeLikelihood` will map to `PL`. I'll keep this open for ADAM 0.18.0.

**Comment by andrewmchen** [comment]
Ah I see it now. Thanks for clarifying!

**Comment by fnothaft** [comment]
No problem!
