### ISSUE TITLE
Upgrade Spark Version

### ISSUE THREAD

**Issue by andrewmchen** [bigdatagenomics/avocado#181]
Adam looks to be on spark version 1.4.1. On avocado, we eventually need a version greater than 1.3.0 that supports gaussian mixture models. Any thoughts on bumping the version up for avocado too?

**Comment by fnothaft** [comment]
We're on 1.4.1 right now: https://github.com/bigdatagenomics/avocado/blob/master/pom.xml#L23 ;)
